### ISSUE TITLE
Missing Collective Package leads to `Class 'Form' not found`

### ISSUE THREAD

**Issue by hpawe01** [atlanticsystems/blog#1]
Hello,

you did not declared Laravel Collective Package in your `composer.json` file. But you use the `Form` alias from them. I had to follow the installation instructions at https://laravelcollective.com/docs/master/html#installation to make this work.

Please update your documentation or add the Laravel Collective Package as dependency.

Thanks

**Comment by bananuki** [comment]
Hello!
Thanks! Updated documentation.
Best Regards
